name: roblox

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to Roblox
        run: rojo upload --asset-id 6398753986 --cookie "$ROBLOSECURITY"
        env:
          ROBLOSECURITY: ${{ secrets.ROBLOSECURITY }}
